import { RoomResponseType } from "@/types/message";

const messageData = [
  {
    id: 1,
    user: {
      id: 1,
      name: "Jake",
      avatar: "images/avatars/1.png",
    },
    unread_count: +(Math.random() * 10).toFixed(),
    messages: [
      {
        id: "1231",
        text: "Hey Finn, what's up?",
        sender_id: "jake",
        type: "text",
        sent_at: "2023-04-20T10:00:00.000Z",
      },
      {
        id: "1232",
        text: "Hey Jake! Not much, just chilling. How about you?",
        sender_id: "finn",
        type: "text",
        sent_at: "2023-04-20T10:01:00.000Z",
      },
      {
        id: "1233",
        text: "I'm on an epic quest with Lady Rainicorn. It's mathematical!",
        sender_id: "jake",
        type: "text",
        sent_at: "2023-04-20T10:02:00.000Z",
      },
      {
        id: "1234",
        text: "Awesome! Where are you headed?",
        sender_id: "finn",
        type: "text",
        sent_at: "2023-04-20T10:03:00.000Z",
      },
      {
        id: "1235",
        text: "We're going to the Candy Kingdom to help Princess Bubblegum",
        sender_id: "jake",
        type: "text",
        sent_at: "2023-04-20T10:04:00.000Z",
      },
      {
        id: "1236",
        text: "Sounds exciting! Be careful out there.",
        sender_id: "finn",
        type: "text",
        sent_at: "2023-04-20T10:05:00.000Z",
      },
      {
        id: "1237",
        text: "Don't worry, we can handle anything that comes our way!",
        sender_id: "jake",
        type: "text",
        sent_at: "2023-04-21T09:00:00.000Z",
      },
      {
        id: "1238",
        text: "That's the spirit! Adventure Time, here we come!",
        sender_id: "finn",
        type: "text",
        sent_at: "2023-04-21T09:01:30.000Z",
      },
    ],
  },
  {
    id: 2,
    user: {
      id: 2,
      name: "Finn",
      avatar: "images/avatars/2.webp",
    },
    unread_count: +(Math.random() * 10).toFixed(),
    messages: [
      {
        id: "2231",
        text: "Hey Jake! Not much, just chilling. How about you?",
        sender_id: "finn",
        type: "text",
        sent_at: "2023-04-20T10:01:00.000Z",
      },
      {
        id: "2232",
        text: "Awesome! Where are you headed?",
        sender_id: "finn",
        type: "text",
        sent_at: "2023-04-20T10:03:00.000Z",
      },
      {
        id: "2233",
        text: "Sounds exciting! Be careful out there.",
        sender_id: "finn",
        type: "text",
        sent_at: "2023-04-20T10:05:00.000Z",
      },
      {
        id: "2234",
        text: "That's the spirit! Adventure Time, here we come!",
        sender_id: "finn",
        type: "text",
        sent_at: "2023-04-21T09:01:30.000Z",
      },
    ],
  },
  {
    id: 3,
    user: {
      id: 3,
      name: "Gunter",
      avatar: "images/avatars/3.jpeg",
    },
    unread_count: +(Math.random() * 10).toFixed(),
    messages: [
      {
        id: "3231",
        text: "Quack quack!",
        sender_id: "gunter",
        type: "text",
        sent_at: "2023-04-20T11:00:00.000Z",
      },
      {
        id: "3232",
        text: "Quack quack quack?",
        sender_id: "gunter",
        type: "text",
        sent_at: "2023-04-20T11:01:00.000Z",
      },
      {
        id: "3233",
        text: "Quack quack quack quack!",
        sender_id: "gunter",
        type: "text",
        sent_at: "2023-04-20T11:02:00.000Z",
      },
      {
        id: "3234",
        text: "Quack quack quack quack quack?",
        sender_id: "gunter",
        type: "text",
        sent_at: "2023-04-20T11:03:00.000Z",
      },
      {
        id: "3235",
        text: "Quack!",
        sender_id: "gunter",
        type: "text",
        sent_at: "2023-04-20T11:04:00.000Z",
      },
    ],
  },
  {
    id: 4,
    user: {
      id: 4,
      name: "Howdy",
      avatar: "images/avatars/4.jpeg",
    },
    unread_count: +(Math.random() * 10).toFixed(),
    messages: [
      {
        id: "4231",
        text: "Howdy, y'all!",
        sender_id: "howdy",
        type: "text",
        sent_at: "2023-04-20T12:00:00.000Z",
      },
      {
        id: "4232",
        text: "How's it going, partner?",
        sender_id: "finn",
        type: "text",
        sent_at: "2023-04-20T12:01:00.000Z",
      },
      {
        id: "4233",
        text: "Yeehaw! Let's have an adventure!",
        sender_id: "howdy",
        type: "text",
        sent_at: "2023-04-20T12:02:00.000Z",
      },
    ],
  },
  {
    id: 5,
    user: {
      id: 5,
      name: "Marceline",
      avatar: "images/avatars/5.jpg",
    },
    unread_count: +(Math.random() * 10).toFixed(),
    messages: [
      {
        id: "5231",
        text: "Hey there, what's going on?",
        sender_id: "marceline",
        type: "text",
        sent_at: "2023-04-20T13:00:00.000Z",
      },
      {
        id: "5232",
        text: "Just jamming with my bass guitar.",
        sender_id: "marceline",
        type: "text",
        sent_at: "2023-04-20T13:01:00.000Z",
      },
      {
        id: "5233",
        text: "Want to join me in a music session?",
        sender_id: "marceline",
        type: "text",
        sent_at: "2023-04-20T13:02:00.000Z",
      },
      {
        id: "5234",
        text: "Absolutely! I'll bring my drums.",
        sender_id: "marceline",
        type: "text",
        sent_at: "2023-04-20T13:03:00.000Z",
      },
    ],
  },
  {
    id: 6,
    user: {
      id: 6,
      name: "Lemongrab",
      avatar: "images/avatars/6.png",
    },
    unread_count: +(Math.random() * 10).toFixed(),
    messages: [
      {
        id: "654321",
        text: "UNACCEPTABLE!!!",
        sender_id: "lemongrab",
        type: "text",
        sent_at: "2023-04-21T15:00:00.000Z",
      },
      {
        id: "654322",
        text: "Calm down, Lemongrab. What seems to be the problem?",
        sender_id: "finn",
        type: "text",
        sent_at: "2023-04-21T15:01:00.000Z",
      },
      {
        id: "654323",
        text: "TOO MUCH SWEETNESS!!!",
        sender_id: "lemongrab",
        type: "text",
        sent_at: "2023-04-21T15:02:00.000Z",
      },
      {
        id: "654324",
        text: "Ah, you must be in the Candy Kingdom. Are the candies causing trouble again?",
        sender_id: "finn",
        type: "text",
        sent_at: "2023-04-21T15:03:00.000Z",
      },
      {
        id: "654325",
        text: "YES!!! THEY MUST BE DISCIPLINED!!!",
        sender_id: "lemongrab",
        type: "text",
        sent_at: "2023-04-21T15:04:00.000Z",
      },
      {
        id: "654326",
        text: "I'll talk to Princess Bubblegum and see if she can address the issue. Hang in there, Lemongrab.",
        sender_id: "finn",
        type: "text",
        sent_at: "2023-04-21T15:05:00.000Z",
      },
    ],
  },
];

export const RoomModel: RoomResponseType[] = messageData;
